import type { BotProfile, Position, Trade } from '@/types'
import { defaultBotRisk } from '@/mocks/bookStore'

/** Historical rows used only by unit tests. The running book does not load these. */

export const sampleTrades: Trade[] = [
  {
    id: 'trd-1001',
    bot_id: 'bot-liquid',
    symbol: 'NVDA',
    type: 'sell',
    quantity: 8,
    price: 119.1,
    timestamp: '2026-09-21T14:12:00.000Z',
    status: 'filled',
    profit_loss: 42.4,
    profit_loss_pct: 0.46,
    reason_code: 'TARGET_HIT',
    shortfall: 0.04,
    regime: 'trend',
    session: 'rth',
  },
  {
    id: 'trd-1002',
    bot_id: 'bot-liquid',
    symbol: 'AAPL',
    type: 'buy',
    quantity: 12,
    price: 227.85,
    timestamp: '2026-09-21T13:46:00.000Z',
    status: 'filled',
    reason_code: 'SCORE_72',
    shortfall: 0.02,
    regime: 'trend',
    session: 'rth',
  },
  {
    id: 'trd-1003',
    bot_id: 'bot-tight',
    symbol: 'AMD',
    type: 'buy',
    quantity: 10,
    price: 164.2,
    timestamp: '2026-09-21T14:05:00.000Z',
    status: 'rejected',
    reason_code: 'NO_TRADE_STALE_DATA',
    shortfall: 0,
    regime: 'transition',
    session: 'rth',
  },
  {
    id: 'trd-1004',
    bot_id: 'bot-liquid',
    symbol: 'MSFT',
    type: 'sell',
    quantity: 4,
    price: 410,
    timestamp: '2026-09-21T15:10:00.000Z',
    status: 'filled',
    profit_loss: -6.2,
    profit_loss_pct: -0.38,
    reason_code: 'STOP_HIT',
    shortfall: 0.15,
    regime: 'range',
    session: 'rth',
  },
]

export const sampleBots: BotProfile[] = [
  {
    id: 'bot-liquid',
    name: 'Liquid leaders',
    status: 'running',
    universe: { top_n: 75, min_price: 5, max_spread_bps: 12 },
    snapshot: { as_of: '', filters: { top_n: 75, min_price: 5, max_spread_bps: 12 }, members: [] },
    risk: { ...defaultBotRisk },
    stats: { marked_pnl: 0, marked_pnl_pct: 0, trade_count: 0, win_rate: 0, expectancy: 0, veto_count: 0 },
  },
  {
    id: 'bot-tight',
    name: 'Tight spreads',
    status: 'stopped',
    universe: { top_n: 50, min_price: 20, max_spread_bps: 10 },
    snapshot: { as_of: '', filters: { top_n: 50, min_price: 20, max_spread_bps: 10 }, members: [] },
    risk: { ...defaultBotRisk },
    stats: { marked_pnl: 0, marked_pnl_pct: 0, trade_count: 0, win_rate: 0, expectancy: 0, veto_count: 0 },
  },
]

export const samplePositions: Position[] = [
  {
    id: 'pos-nvda',
    bot_id: 'bot-liquid',
    symbol: 'NVDA',
    quantity: 8,
    entry_price: 117.4,
    current_price: 118.62,
    unrealized_pnl: 9.76,
    realized_pnl: 0,
    opened_at: '2026-09-22T13:40:00.000Z',
    is_open: true,
    score: 74,
    veto_code: null,
    regime: 'trend',
    expected_cost: 1.8,
    realized_cost: 0.42,
    hold_minutes: 48,
    atr_stop: 115.9,
    target_price: 120.2,
    open_stop_risk: 21.76,
  },
  {
    id: 'pos-aapl',
    bot_id: 'bot-liquid',
    symbol: 'AAPL',
    quantity: 12,
    entry_price: 227.85,
    current_price: 228.4,
    unrealized_pnl: 6.6,
    realized_pnl: 0,
    opened_at: '2026-09-22T14:05:00.000Z',
    is_open: true,
    score: 72,
    veto_code: null,
    regime: 'trend',
    expected_cost: 2.1,
    realized_cost: 0.55,
    hold_minutes: 22,
    atr_stop: 225.4,
    target_price: 232.1,
    open_stop_risk: 29.4,
  },
]
